
--
--  grbsrc Installation Script
--
--  Must be run as a SYSTEM User (DBA)
--
-- Command Line Parameters:
--   1 - INSTALL_SYSTEM_CONNECT: SYSTEM/password@TNSALIAS
--       i.e. pass the username and password for the SYSTEM user
--            and the TNSALIAS for the connection to the database.
--       The Data Load installation requires this connection information.
--

spool install_grbsrc.log

define INSTALL_SYSTEM_CONNECT="&1."

-- Must Set SQLPREFIX away from "#" Oracle Change Data Capture packages
set sqlprefix "~"

-- Using "^P", CHR(16), DLE as an escape character
set escape OFF
set escape ""

----------------------------------------
--  Prepare for Install
@db_install.sql "./installation_prepare.sql" "" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- PACKAGE Install

@db_install.sql "ODBCAPTURE/COMMON_UTIL.pspec" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/GRAB_SCRIPTS.pspec" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ROOT_SCRIPTS.pspec" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ZIP_UTIL_PKG.pspec" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- TABLE Install

@db_install.sql "ODBCAPTURE/DBA_DEPENDENCIES_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/DBA_OBJECTS_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/DBA_TAB_PRIVS_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/DLOAD_CONF.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/INSTALL_TYPE_TIMING.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJECT_CONF.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_COMMENTS_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_CONTEXT_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_DATA_LOAD_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_FKEY_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_INDEX_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_OBJECT_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_SYNONYM_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_TRIGGER_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OTYPE_CONF.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ROLE_CONF.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/SCHEMA_CONF.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/TYPE_CONF.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ZIP_FILES.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ZX_OBJ_INSTALL_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ZX_PRIV_ALL_TAB.tab" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- DATA_LOAD Install

@db_install.sql "ODBCAPTURE/DLOAD_CONF.cdl" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJECT_CONF.cdl" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OTYPE_CONF.cdl" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ROLE_CONF.cdl" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/SCHEMA_CONF.cdl" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/TYPE_CONF.cdl" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- INDEX Install

@db_install.sql "ODBCAPTURE/DBA_DEPENDENCIES_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/DBA_OBJECTS_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/DBA_TAB_PRIVS_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_COMMENTS_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_CONTEXT_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_DATA_LOAD_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_FKEY_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_INDEX_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_OBJECT_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_SYNONYM_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_TRIGGER_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ZX_OBJ_INSTALL_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ZX_PRIV_ALL_TAB.tabind" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- VIEW Install

@db_install.sql "ODBCAPTURE/AQ_SYSTEM_PRIVS_VW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/DBA_DEPENDENCIES_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/DBA_OBJECTS_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/DBA_TAB_PRIVS_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_COMMENTS_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_CONTEXT_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_DATA_LOAD_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_FKEY_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_INDEX_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_OBJECT_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_SYNONYM_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJ_INSTALL_TRIGGER_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/PRIV_OBJ_DIR_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/PRIV_OBJ_INSTALL_VW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/PRIV_OBJ_JAVA_FG_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/PRIV_OBJ_QUEUE_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/PRIV_OBJ_XDBACL_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/PRIV_QUEUE_REGISTER_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/PRIV_QUEUE_SUBSCRIBE_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/PRIV_QUEUE_SYSPRIVS_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/PRIV_ROLE_PRIVILEGES_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/PRIV_SYSOBJ_PRIVILEGES_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/PRIV_SYSTEM_PRIVILEGES_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/SCHEMA_OBJECTS_VW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/UOR_INSTALL_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ZX_OBJ_INSTALL_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ZX_PRIV_ALL_VIEW.vw" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- PACKAGE BODY Install

@db_install.sql "ODBCAPTURE/COMMON_UTIL.pbody" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/GRAB_SCRIPTS.pbody" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ROOT_SCRIPTS.pbody" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ZIP_UTIL_PKG.pbody" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- TABLE_FOREIGN_KEY Install

@db_install.sql "ODBCAPTURE/DLOAD_CONF.tabfk" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/OBJECT_CONF.tabfk" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/ROLE_CONF.tabfk" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/SCHEMA_CONF.tabfk" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."
@db_install.sql "ODBCAPTURE/TYPE_CONF.tabfk" "ODBCAPTURE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- Finalize Installation
@db_install.sql "./installation_finalize.sql" "" "&INSTALL_SYSTEM_CONNECT."

spool off

