OPTIONS (SKIP=1)
LOAD DATA
INTO TABLE "ODBCAPTURE"."BUILD_PATH"
APPEND
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (PARENT_BUILD_SEQ               FLOAT EXTERNAL
   ,BUILD_SEQ                      FLOAT EXTERNAL
   )
