OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "ODBCAPTURE"."TYPE_CONF"
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (INSTALL_TYPE                   CHAR(10)
   ,NOTES                          CHAR(1024)
   ,INSTALL_TYPE_PARENT            CHAR(10)
   )
