
--
--  Create WTP.WT_EXECUTE_TEST_RUNNER Procedure
--

set define off


--DBMS_METADATA:WTP.WT_EXECUTE_TEST_RUNNER

  CREATE OR REPLACE EDITIONABLE PROCEDURE "WTP"."WT_EXECUTE_TEST_RUNNER" 
   authid current_user
   -- AUTHID CURRENT_USER is required for assertions with dynamic PL/SQL execution.
is
   sql_txt  varchar2(4000);
begin
   sql_txt := 'begin "' || wtp.core_data.g_run_rec.test_runner_owner ||
                  '"."' || wtp.core_data.g_run_rec.test_runner_name  ||
                   '".' || wtplsql.C_RUNNER_ENTRY_POINT          || '; end;';
   --dbms_output.put_line(sql_txt);
   execute immediate sql_txt;
end wt_execute_test_runner;
/


--  Grants
grant EXECUTE on "WTP"."WT_EXECUTE_TEST_RUNNER" to "PUBLIC";


--  Synonyms


set define on
