
--
--  Create WTP.JUNIT_XML_PERSIST_ALL Procedure
--

set define off


--DBMS_METADATA:WTP.JUNIT_XML_PERSIST_ALL

  CREATE OR REPLACE EDITIONABLE PROCEDURE "WTP"."JUNIT_XML_PERSIST_ALL" 
is
   procedure p (in_line in varchar2) is
   begin
      DBMS_OUTPUT.PUT_LINE(in_line);
   end p;
begin
   p('<?xml version="1.0" encoding="UTF-8"?>');
   p('<!-- http://dmdiet.com - Adapted to SQLDeveloper Unit Test Utility -->');
   p('<!-- http://nelsonwells.net/2012/09/how-jenkins-ci-parses-and-displays-junit-output/ -->');
   p('<!-- Jenkins identifies the failed tests as {package}.{class}.{test}. -->');
   p('<testsuites>');
   for suites in (
      select run.start_dtm
            ,run.end_dtm
            ,run.id
            ,tr.owner || '.' || tr.name      SUITE_NAME
            ,nvl(db.owner, tr.owner)         PACKAGE_NAME
            ,case when db.name || db.type is null
                  then 'TEST_RUNNER'
                  else db.name || ':' || db.type
             end                             CLASS_NAME
            ,run.tc_cnt
            ,run.tc_fail
            ,extract(day from (run.end_dtm -
                               run.start_dtm) * 86400000)
                                             TOT_INTERVAL_MSEC
            ,run.error_message
       from  wt_test_runs  run
             join wt_test_runners  tr
                  on tr.id = run.test_runner_id
        left join wt_dbouts  db
                  on  db.id = run.dbout_id
       where run.is_last_run = wt_test_run.get_last_run_flag
       order by run.start_dtm, run.id )
   loop
      p('  <testsuite name="' || suites.suite_name ||
                  '" tests="' || suites.tc_cnt ||
               '" failures="' || suites.tc_fail ||
                   '" time="' || suites.tot_interval_msec ||
              '" timestamp="' || to_char(suites.start_dtm,'YYYY-MM-DD"T"HH24:MI:SS') ||
                         '">' );
      for cases in (
         select run.id
               ,tc.testcase
               ,tcr.testcase_id
               ,tcr.asrt_cnt                    ASSERTS
               ,tcr.asrt_fail                   FAILURES
               ,nvl(tcr.asrt_tot_msec
                   ,suites.tot_interval_msec)   TOT_INTERVAL_MSEC
          from  wt_test_runs  run
           left join wt_testcase_runs  tcr
                     on  tcr.test_run_id = run.id
           left join wt_testcases  tc
                     on  tc.id = tcr.testcase_id
          where run.id = suites.id
          order by testcase )
      loop
         if     nvl(cases.failures,1) = 0
            and suites.error_message is null
         then
            p('    <testcase name="' || nvl(cases.testcase,'NULL') ||
                      '" classname="' || suites.suite_name ||
                      '" time="' || cases.tot_interval_msec || '"/>');
         else
            p('    <testcase name="' || nvl(cases.testcase,'NULL') ||
                      '" classname="' || suites.package_name || '.' || suites.class_name ||
                           '" time="' || cases.tot_interval_msec || '">');
            p('      <error message="' || nvl(to_char(cases.failures),'No') || ' assertion failures. ' ||
                                          suites.error_message || '">');
            -- Print each of the non-passing results
            for asrts in (
               select wtr.result_seq
                     ,wtr.status
                     ,wtr.interval_msec
                     ,wtr.message
                     ,wtr.assertion
                     ,wtr.details
                from  wt_results  wtr
                where wtr.test_run_id = suites.id
                 and  (   (  cases.testcase_id is null
                           and wtr.testcase_id is null)
                       or wtr.testcase_id = cases.testcase_id)
                 and  wtr.status != 'PASS'
                order by wtr.result_seq )
            loop
               p(lpad(asrts.result_seq,4)    || ': '  ||
                 rpad(asrts.status,4)        || ' '   ||
                 lpad(asrts.interval_msec,4) || 'ms ' ||
                 asrts.message               ||  '. ' ||
                 asrts.assertion             || ' - ' ||
                 replace(replace(asrts.details
                                ,CHR(13),'\r')
                        ,CHR(10),'\n')       || '.'   );
            end loop;
            p('      </error>');
            p('    </testcase>');
         end if;
      end loop;
   end loop;
   p('  </testsuite>');
   p('</testsuites>');
end junit_xml_persist_all;
/


--  Grants


--  Synonyms


set define on
